apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cloudflare-warp
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  - "extensions"
  resources:
  - ingresses
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
