apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cloudflare-warp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudflare-warp
subjects:
- kind: ServiceAccount
  name: cloudflare-warp
