apiVersion: apps/v1
kind: Deployment
metadata:
  name: julianvmodesto-web
  labels:
    app: julianvmodesto-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: julianvmodesto-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: julianvmodesto-web
    spec:
      containers:
      - name: caddy
        image: gcr.io/julian-modesto/caddy
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8888
          name: health
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/caddy/Caddyfile
          name: caddyfile
          subPath: Caddyfile
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
          defaultMode: 420
