apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: julianvmodesto-web
  labels:
    app: julianvmodesto-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: julianvmodesto-web
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      containers:
      - name: caddy
        image: julianvmodesto/caddy
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: health
          containerPort: 8888
        livenessProbe:
          httpGet:
            path: /
            port: health
        readinessProbe:
          httpGet:
            path: /
            port: health
        volumeMounts:
          # Mount Caddyfile only, not all of /etc
        - name: caddyfile
          mountPath: /etc/Caddyfile
          subPath: Caddyfile

