apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: julianvmodesto-web
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       julianvmodesto-web
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: istio-proxy
      mode: "Off"
