name: Build and Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  PROJECT_ID: julian-modesto
  RUN_REGION: us-central1
  SERVICE_NAME: julianvmodesto-web

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/307322809497/locations/global/workloadIdentityPools/pool-0/providers/github-actions'
        service_account: 'julianvmodesto-web-run-release@julian-modesto.iam.gserviceaccount.com'
        
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: julian-modesto

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
          
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
